create table if not exists public.perfis (
    id uuid primary key references auth.users(id) on delete cascade,
    nome text not null check (nome in ('MASTER', 'FINANCEIRO', 'CONFIRMADOR')),
    criado_em timestamptz not null default now()
);

create table if not exists public.funcionarios (
    id bigint generated by default as identity primary key,
    nome text not null,
    admissao date,
    banco text,
    chave_pix text,
    salario_liquido numeric(12, 2) not null default 0,
    adiantamento numeric(12, 2) not null default 0,
    va numeric(12, 2) not null default 0,
    desconto numeric(12, 2) not null default 0,
    ativo boolean not null default true,
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now()
);

create table if not exists public.configs (
    id integer primary key default 1 check (id = 1),
    dia_salario smallint not null default 5,
    dia_adiantamento smallint not null default 20,
    atualizado_em timestamptz not null default now(),
    constraint configs_dia_salario_check check (dia_salario between 1 and 31),
    constraint configs_dia_adiantamento_check check (dia_adiantamento between 1 and 31)
);

create table if not exists public.historico_pagamentos (
    id bigint generated by default as identity primary key,
    funcionario_id bigint not null references public.funcionarios(id),
    tipo text not null check (tipo in ('Salário+VA', 'Adiantamento')),
    valor numeric(12, 2) not null check (valor >= 0),
    mes smallint not null check (mes between 1 and 12),
    ano smallint not null check (ano between 2000 and 2200),
    status text not null default 'PENDENTE' check (status in ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    criado_por uuid not null references auth.users(id),
    confirmado_por uuid references auth.users(id),
    criado_em timestamptz not null default now(),
    confirmado_em timestamptz,
    constraint pagamento_confirmado_consistente check (
        (status = 'CONFIRMADO' and confirmado_por is not null and confirmado_em is not null)
        or (status <> 'CONFIRMADO')
    ),
    constraint pagamento_unico_por_tipo unique (funcionario_id, tipo, mes, ano)
);

create table if not exists public.pagamentos (
    id bigint generated by default as identity primary key,
    funcionario_id bigint references public.funcionarios(id),
    mes smallint not null check (mes between 1 and 12),
    ano smallint not null check (ano between 2000 and 2200),
    valor numeric(12, 2) not null default 0,
    status text not null default 'PENDENTE' check (status in ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    criado_por uuid references auth.users(id),
    confirmado_por uuid references auth.users(id),
    criado_em timestamptz not null default now(),
    confirmado_em timestamptz
);

insert into public.configs (id, dia_salario, dia_adiantamento)
values (1, 5, 20)
on conflict (id) do nothing;

create index if not exists idx_funcionarios_ativos_nome
    on public.funcionarios (ativo, nome);

create index if not exists idx_historico_pagamentos_periodo
    on public.historico_pagamentos (mes, ano);

create index if not exists idx_historico_pagamentos_status
    on public.historico_pagamentos (status);

create or replace function public.usuario_tem_perfil(perfis_permitidos text[])
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select exists (
        select 1
        from public.perfis
        where id = auth.uid()
          and nome = any(perfis_permitidos)
    );
$$;

alter table public.perfis enable row level security;
alter table public.funcionarios enable row level security;
alter table public.configs enable row level security;
alter table public.historico_pagamentos enable row level security;
alter table public.pagamentos enable row level security;

create policy "usuario consulta o proprio perfil"
    on public.perfis for select
    to authenticated
    using (id = auth.uid());

create policy "usuarios autenticados consultam funcionarios"
    on public.funcionarios for select
    to authenticated
    using (true);

create policy "master cria funcionarios"
    on public.funcionarios for insert
    to authenticated
    with check (public.usuario_tem_perfil(array['MASTER']));

create policy "master altera funcionarios"
    on public.funcionarios for update
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER']))
    with check (public.usuario_tem_perfil(array['MASTER']));

create policy "master exclui funcionarios"
    on public.funcionarios for delete
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER']));

create policy "usuarios autenticados consultam configuracoes"
    on public.configs for select
    to authenticated
    using (true);

create policy "master altera configuracoes"
    on public.configs for update
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER']))
    with check (public.usuario_tem_perfil(array['MASTER']));

create policy "usuarios autenticados consultam historico"
    on public.historico_pagamentos for select
    to authenticated
    using (true);

create policy "financeiro registra pagamentos"
    on public.historico_pagamentos for insert
    to authenticated
    with check (
        criado_por = auth.uid()
        and public.usuario_tem_perfil(array['MASTER', 'FINANCEIRO'])
    );

create policy "confirmador confirma pagamentos"
    on public.historico_pagamentos for update
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER', 'CONFIRMADOR']))
    with check (
        public.usuario_tem_perfil(array['MASTER', 'CONFIRMADOR'])
        and (
            status <> 'CONFIRMADO'
            or (confirmado_por = auth.uid() and confirmado_em is not null)
        )
    );

create policy "master exclui historico"
    on public.historico_pagamentos for delete
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER']));

create policy "usuarios autenticados consultam pagamentos"
    on public.pagamentos for select
    to authenticated
    using (true);

create policy "usuarios autorizados criam pagamentos"
    on public.pagamentos for insert
    to authenticated
    with check (public.usuario_tem_perfil(array['MASTER', 'FINANCEIRO']));

create policy "usuarios autorizados alteram pagamentos"
    on public.pagamentos for update
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER', 'CONFIRMADOR']))
    with check (public.usuario_tem_perfil(array['MASTER', 'CONFIRMADOR']));

create policy "master exclui pagamentos"
    on public.pagamentos for delete
    to authenticated
    using (public.usuario_tem_perfil(array['MASTER']));